### ISSUE TITLE
Broken in 2.7

### ISSUE THREAD

**Issue by asottile** [csvoss/oneliner#5]
```
root@375204ecfbb3:/oneliner# ./unittest.sh 
E.E..EE.E.......EE.EEEEEEE...EE....E
======================================================================
ERROR: test_11lines (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda REFRAIN: (lambda bottles_of_beer: (__y(lambda __this: (lambda (USED_VARS): (lambda __after: (lambda ___: (lambda bottles_of_beer: __this((USED_VARS)))(bottles_of_beer-1))(__print((REFRAIN%(bottles_of_beer,bottles_of_beer,(bottles_of_beer-1))))) if bottles_of_beer>1 else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): None))))((USED_VARS)))(99))('\n%d bottles of beer on the wall,\n%d bottles of beer,\ntake one down, pass it around,\n%d bottles of beer on the wall!\n'))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'USED_VARS' is not defined


======================================================================
ERROR: test_16lines (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda csv: (lambda writer: (lambda ___: (lambda stocks: (lambda status_labels: (lambda (MODIFIED_VARS): None)(reduce((lambda (MOD_VARS_USED), (ticker,name,price,change,pct): (lambda status: (lambda ___: (MODIFIED_VARS))(__print(('%s is %s (%s%%)'%(name,status,pct)))))(status_labels[cmp(float(change),0.0)])), stocks, (MOD_VARS_USED))))({-1:'down',0:'unchanged',1:'up'}))(csv.reader(open('stocks.csv','rb'))))(writer.writerows([('GOOG','Google, Inc.',505.24,0.47,0.09),('YHOO','Yahoo! Inc.',27.38,0.33,1.22),('CNET','CNET Networks, Inc.',8.62,-0.13,-1.49)])))(csv.writer(open('stocks.csv','wb',buffering=0))))(__import__('csv')))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MOD_VARS_USED' is not defined


======================================================================
ERROR: test_3lines (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda friends: (lambda (MODIFIED_VARS): None)(reduce((lambda (MOD_VARS_USED), (i,name): (lambda ___: (MODIFIED_VARS))(__print('iteration {iteration} is {name}'.format(iteration=i,name=name)))), enumerate(friends), (MOD_VARS_USED))))(['john','pat','gary','michael']))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MOD_VARS_USED' is not defined


======================================================================
ERROR: test_4lines (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda (parents,babies): (__y(lambda __this: (lambda (USED_VARS): (lambda __after: (lambda ___: (lambda (parents,babies): __this((USED_VARS)))((babies,(parents+babies))))(__print('This generation has {0} babies'.format(babies))) if babies<100 else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): None))))((USED_VARS)))((1,1)))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'USED_VARS' is not defined


======================================================================
ERROR: test_6lines (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda re: (lambda (MODIFIED_VARS): None)(reduce((lambda (MOD_VARS_USED), test_string: (lambda __after: (lambda ___: __after((MODIFIED_VARS)))(__print(test_string,'is a valid US local phone number')) if re.match('^\\d{3}-\\d{4}$',test_string) else (lambda ___: __after((MODIFIED_VARS)))(__print(test_string,'rejected')))(lambda (MODIFIED_VARS): (MODIFIED_VARS))), ['555-1212','ILL-EGAL'], (MOD_VARS_USED))))(__import__('re')))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MOD_VARS_USED' is not defined


======================================================================
ERROR: test_fibonacci (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda x: (lambda y: (lambda counter: (__y(lambda __this: (lambda (USED_VARS): (lambda __after: (lambda counter: (lambda (x,y): (lambda ___: __this((USED_VARS)))(__print(x)))((y,(x+y))))(counter+1) if counter<15 else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): None))))((USED_VARS)))(0))(1))(0))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'USED_VARS' is not defined


======================================================================
ERROR: test_for (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda x: (lambda (MODIFIED_VARS): __print(x))(reduce((lambda (MOD_VARS_USED), i: (lambda x: (MODIFIED_VARS))((x+i))), range(5), (MOD_VARS_USED))))(5))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MOD_VARS_USED' is not defined


======================================================================
ERROR: test_guess_my_number (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda guess_my_number: (lambda ___: None)(guess_my_number(42)))(lambda n:(__y(lambda __this: (lambda (USED_VARS): (lambda __after: (lambda user_input: (lambda __after: (lambda ___: __after((MODIFIED_VARS)))(__print('Not a positive integer!')) if (len(user_input)==0 or (not user_input.isdigit())) else (lambda user_input: (lambda __after: (lambda ___: __after((MODIFIED_VARS)))(__print('Too big! Try again!')) if user_input>n else (lambda __after: (lambda ___: __after((MODIFIED_VARS)))(__print('Too small! Try again!')) if user_input<n else (lambda ___: True)(__print('You win!')))(lambda (MODIFIED_VARS): __after((MODIFIED_VARS))))(lambda (MODIFIED_VARS): __after((MODIFIED_VARS))))(int(user_input)))(lambda (MODIFIED_VARS): __this((USED_VARS))))(raw_input('Enter a positive integer to guess: ')) if True else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): None))))((USED_VARS))))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'USED_VARS' is not defined


======================================================================
ERROR: test_if (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda x: (lambda __after: (lambda x: __after((MODIFIED_VARS)))(5) if True else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): __print(x)))(7))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MODIFIED_VARS' is not defined


======================================================================
ERROR: test_if_comprehensive (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda x: (lambda __after: (lambda x: __after((MODIFIED_VARS)))(2) if True else (lambda x: __after((MODIFIED_VARS)))(3))(lambda (MODIFIED_VARS): (lambda ___: (lambda __after: (lambda x: __after((MODIFIED_VARS)))(4) if False else (lambda x: __after((MODIFIED_VARS)))(5))(lambda (MODIFIED_VARS): __print(x)))(__print(x))))(1))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MODIFIED_VARS' is not defined


======================================================================
ERROR: test_ifelifelse (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda x: (lambda __after: (lambda x: __after((MODIFIED_VARS)))(2) if False else (lambda __after: (lambda x: __after((MODIFIED_VARS)))(6) if True else (lambda x: __after((MODIFIED_VARS)))(7))(lambda (MODIFIED_VARS): __after((MODIFIED_VARS))))(lambda (MODIFIED_VARS): __print(x)))(1))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MODIFIED_VARS' is not defined


======================================================================
ERROR: test_ifelifelse_comprehensive (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda x: (lambda __after: (lambda x: __after((MODIFIED_VARS)))(2) if True else (lambda __after: (lambda x: __after((MODIFIED_VARS)))(3) if False else (lambda x: __after((MODIFIED_VARS)))(4))(lambda (MODIFIED_VARS): __after((MODIFIED_VARS))))(lambda (MODIFIED_VARS): (lambda ___: (lambda __after: (lambda x: __after((MODIFIED_VARS)))(5) if False else (lambda __after: (lambda x: __after((MODIFIED_VARS)))(6) if True else (lambda x: __after((MODIFIED_VARS)))(7))(lambda (MODIFIED_VARS): __after((MODIFIED_VARS))))(lambda (MODIFIED_VARS): (lambda ___: (lambda __after: (lambda x: __after((MODIFIED_VARS)))(8) if False else (lambda __after: (lambda x: __after((MODIFIED_VARS)))(9) if False else (lambda x: __after((MODIFIED_VARS)))(10))(lambda (MODIFIED_VARS): __after((MODIFIED_VARS))))(lambda (MODIFIED_VARS): __print(x)))(__print(x))))(__print(x))))(1))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MODIFIED_VARS' is not defined


======================================================================
ERROR: test_ifelse (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda x: (lambda __after: (lambda x: __after((MODIFIED_VARS)))(5) if x>8 else (lambda x: __after((MODIFIED_VARS)))(10))(lambda (MODIFIED_VARS): __print(x)))(7))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MODIFIED_VARS' is not defined


======================================================================
ERROR: test_ifelse_comprehensive (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda x: (lambda __after: (lambda x: __after((MODIFIED_VARS)))(2) if True else (lambda x: __after((MODIFIED_VARS)))(3))(lambda (MODIFIED_VARS): (lambda ___: (lambda __after: (lambda x: __after((MODIFIED_VARS)))(4) if False else (lambda x: __after((MODIFIED_VARS)))(5))(lambda (MODIFIED_VARS): __print(x)))(__print(x))))(1))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MODIFIED_VARS' is not defined


======================================================================
ERROR: test_name_main (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda __after: (lambda ___: __after((MODIFIED_VARS)))(__print('Pass!')) if __name__=='__main__' else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): None))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MODIFIED_VARS' is not defined


======================================================================
ERROR: test_prime_tester (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda math: (lambda is_prime: (lambda smallest_prime_larger_than: (lambda ___: (lambda ___: (lambda ___: (lambda ___: (lambda ___: (lambda ___: (lambda ___: (lambda ___: (lambda ___: (lambda ___: __print(smallest_prime_larger_than(1000)))(__print(smallest_prime_larger_than(91))))(__print(smallest_prime_larger_than(1))))(__print(is_prime(89))))(__print(is_prime(91))))(__print(is_prime(45))))(__print(is_prime(5))))(__print(is_prime(4))))(__print(is_prime(3))))(__print(is_prime(2))))(__print(is_prime(1))))(lambda x:(__y(lambda __this: (lambda (USED_VARS): (lambda __after: (lambda x: (lambda __after: x if is_prime(x) else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): __this((USED_VARS))))((x+1)) if True else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): None))))((USED_VARS))))(lambda n:(lambda __after: False if n<2 else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): (lambda __after: True if n==2 else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): (lambda n: (lambda factors: (lambda i: (__y(lambda __this: (lambda (USED_VARS): (lambda __after: (lambda factor: (lambda __after: False if (n%factor)==0 else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): (lambda i: __this((USED_VARS)))((i+1))))(factors[i]) if i<len(factors) else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): True))))((USED_VARS)))(0))(range(2,int((math.ceil(math.sqrt(n))+1)))))(int(n))))))(__import__('math')))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'MODIFIED_VARS' is not defined


======================================================================
ERROR: test_while (runtests.TestOneLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 20, in new_test
    capture_exec(onelined),
  File "runtests.py", line 43, in capture_exec
    raise type(e)(code_string + '\n\n' + exc)
NameError: (lambda __builtin__: (lambda __y, __print: (lambda x: (__y(lambda __this: (lambda (USED_VARS): (lambda __after: (lambda x: (lambda ___: __this((USED_VARS)))(__print(x)))((x-1)) if x>0 else __after((MODIFIED_VARS)))(lambda (MODIFIED_VARS): __print('Done!')))))((USED_VARS)))(5))((lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))), __builtin__.__dict__['print']))(__import__('__builtin__'))

Traceback (most recent call last):
  File "runtests.py", line 39, in capture_exec
    exec code_string in namespace
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
  File "<string>", line 1, in <lambda>
NameError: global name 'USED_VARS' is not defined


----------------------------------------------------------------------
Ran 36 tests in 0.030s

FAILED (errors=17)
```

Easy to reproduce with

`docker run -ti ubuntu:vivid bash` (or travis-ci's installed version of python2.7)

**Comment by asottile** [comment]
Here's an expansion of test_while on 2.7.9:

```python
(lambda __builtin__: (
    lambda __y, __print: (
        lambda x: (
            __y(
                lambda __this: (
                    lambda (USED_VARS): (
                        lambda __after: (
                            lambda x: (
                                lambda ___: __this(
                                    (USED_VARS)
                                )
                            )(__print(x))
                        )((x-1)) if x>0 else __after((MODIFIED_VARS))
                    )(
                        lambda (MODIFIED_VARS): __print('Done!')
                    )
                )
            )
        )((USED_VARS))
    )(5))(
        (lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))),
        __builtin__.__dict__['print']
    )
)(__import__('__builtin__'))
```

**Comment by asottile** [comment]
Actually,this seems entirely broken in py27.  Regression was introduced here: 9931ac90e5b75c2c8b3c7ba438e4b8062d15fd93

**Comment by csvoss** [comment]
Thanks!

I was in the process of totally rearranging the architecture of this file a while ago -- I wasn't expecting it to be posted to Hacker News :). I've reverted it to an older edition that works. Let me know if you're still encountering this issue?

**Comment by asottile** [comment]
Seems fixed
